<?php
/**
 * Invoice generation: branded Arabic HTML invoices with signed URLs.
 *
 * @package Lexi_API
 */

defined('ABSPATH') || exit;

class Lexi_Invoices
{

    /**
     * Generate a signed URL for an order invoice.
     *
     * @param int    $order_id Order ID.
     * @param string $type     "provisional" or "final".
     * @return string Signed URL valid for 1 hour.
     */
    public static function get_signed_url(int $order_id, string $type = 'provisional'): string
    {
        $base_url = rest_url(LEXI_API_NAMESPACE . '/invoices/render');
        $base_url = add_query_arg(
            array(
                'order_id' => $order_id,
                'type' => $type,
            ),
            $base_url
        );

        return Lexi_Security::generate_signed_url($base_url);
    }

    /**
     * Generate a permanent verification URL for an order invoice.
     *
     * @param WC_Order $order WooCommerce order.
     * @return string Signed verification URL.
     */
    public static function get_verification_url(WC_Order $order): string
    {
        $base_url = rest_url(LEXI_API_NAMESPACE . '/invoices/verify');
        return add_query_arg(
            array(
                'order_id' => (int) $order->get_id(),
                'sig' => self::build_current_verification_signature($order),
            ),
            $base_url
        );
    }

    /**
     * Validate invoice verification signature.
     *
     * @param WC_Order $order WooCommerce order.
     * @param string   $sig   Signature from request.
     * @return bool
     */
    public static function verify_signature(WC_Order $order, string $sig): bool
    {
        $provided_variants = self::normalize_provided_signature_variants($sig);
        if (empty($provided_variants)) {
            return false;
        }

        foreach ($provided_variants as $provided) {
            if (self::matches_order_stored_signature($order, $provided)) {
                return true;
            }
        }

        $candidates = array(
            self::build_current_verification_signature($order),
        );

        foreach (self::build_legacy_signature_payloads($order) as $payload) {
            foreach (self::build_signature_candidates($payload) as $candidate) {
                $candidates[] = $candidate;
            }
        }

        $candidates = array_values(array_unique(array_filter($candidates, static function ($candidate): bool {
            return is_string($candidate) && '' !== $candidate;
        })));

        foreach ($provided_variants as $provided) {
            foreach ($candidates as $candidate) {
                if (hash_equals($candidate, $provided)) {
                    return true;
                }

                // Backward compatibility for historically truncated links (40 chars).
                if (40 === strlen($provided) && strlen($candidate) >= 40) {
                    $prefix = substr($candidate, 0, 40);
                    if (is_string($prefix) && hash_equals($prefix, $provided)) {
                        return true;
                    }
                }
            }
        }

        return false;
    }

    /**
     * Build normalized variants of a provided signature value.
     *
     * Some PDF viewers may inject separators when auto-detecting long URLs.
     * We accept an additional hex-only variant to keep verification stable.
     *
     * @param string $sig Signature from request.
     * @return array<int,string>
     */
    private static function normalize_provided_signature_variants(string $sig): array
    {
        $raw = strtolower(trim(rawurldecode($sig)));
        if ('' === $raw) {
            return array();
        }

        $variants = array($raw);
        $hex_only = preg_replace('/[^a-f0-9]/', '', $raw);
        if (is_string($hex_only) && '' !== $hex_only && $hex_only !== $raw) {
            $variants[] = $hex_only;
        }

        return array_values(array_unique($variants));
    }

    /**
     * Compare provided signature with values already stored on the order.
     *
     * This is a safe compatibility path for old invoices generated by previous
     * implementations where tokens/signatures were persisted in order meta.
     *
     * @param WC_Order $order    WooCommerce order.
     * @param string   $provided Normalized provided signature.
     * @return bool
     */
    private static function matches_order_stored_signature(WC_Order $order, string $provided): bool
    {
        $meta_keys = array(
            '_invoice_verify_sig',
            '_invoice_verify_signature',
            '_invoice_verify_token',
            '_lexi_invoice_verify_sig',
            '_lexi_invoice_verify_signature',
            '_lexi_invoice_verify_token',
        );

        $stored_values = array();
        foreach ($meta_keys as $key) {
            $value = trim((string) $order->get_meta($key));
            if ('' !== $value) {
                $stored_values[] = $value;
            }
        }

        $stored_values = array_values(array_unique($stored_values));
        if (empty($stored_values)) {
            return false;
        }

        foreach ($stored_values as $stored) {
            $normalized = strtolower(trim($stored));
            if ('' === $normalized) {
                continue;
            }

            if (hash_equals($normalized, $provided)) {
                return true;
            }

            if (40 === strlen($provided) && strlen($normalized) >= 40) {
                $prefix = substr($normalized, 0, 40);
                if (is_string($prefix) && hash_equals($prefix, $provided)) {
                    return true;
                }
            }
        }

        $derived = array();
        foreach ($stored_values as $stored) {
            $normalized = trim((string) $stored);
            if ('' === $normalized) {
                continue;
            }

            $derived[] = hash('sha256', $normalized);
            $derived[] = hash('sha1', $normalized);
            $derived[] = hash('md5', $normalized);

            foreach (self::signature_secrets() as $secret) {
                if ('' === $secret) {
                    continue;
                }

                $derived[] = hash_hmac('sha256', $normalized, $secret);
                $derived[] = hash_hmac('sha1', $normalized, $secret);
                $derived[] = hash_hmac('md5', $normalized, $secret);
                $derived[] = hash('sha256', $normalized . '|' . $secret);
                $derived[] = hash('sha1', $normalized . '|' . $secret);
                $derived[] = hash('md5', $normalized . '|' . $secret);
                $derived[] = hash('sha256', $secret . '|' . $normalized);
                $derived[] = hash('sha1', $secret . '|' . $normalized);
                $derived[] = hash('md5', $secret . '|' . $normalized);
            }
        }

        $derived = array_values(array_unique(array_filter($derived, static function ($candidate): bool {
            return is_string($candidate) && '' !== $candidate;
        })));

        foreach ($derived as $candidate) {
            if (hash_equals($candidate, $provided)) {
                return true;
            }
            if (40 === strlen($provided) && strlen($candidate) >= 40) {
                $prefix = substr($candidate, 0, 40);
                if (is_string($prefix) && hash_equals($prefix, $provided)) {
                    return true;
                }
            }
        }

        return false;
    }

    /**
     * Build the current verification signature.
     *
     * @param WC_Order $order WooCommerce order.
     * @return string
     */
    private static function build_current_verification_signature(WC_Order $order): string
    {
        $payload = implode('|', array(
            'lexi_invoice_verify',
            (string) $order->get_id(),
            (string) $order->get_order_key(),
        ));

        return hash_hmac('sha256', $payload, (string) wp_salt('auth'));
    }

    /**
     * Build legacy payload variants to keep old QR links valid.
     *
     * @param WC_Order $order WooCommerce order.
     * @return array<int,string>
     */
    private static function build_legacy_signature_payloads(WC_Order $order): array
    {
        $created = $order->get_date_created();
        $order_id = (string) $order->get_id();
        $order_number = (string) $order->get_order_number();
        $order_key = (string) $order->get_order_key();
        $verify_token = trim((string) $order->get_meta('_invoice_verify_token'));

        $total_value = (float) $order->get_total();
        $totals = array_values(array_unique(array_filter(array(
            (string) wc_format_decimal($order->get_total(), 2),
            (string) wc_format_decimal($order->get_total(), 1),
            (string) wc_format_decimal($order->get_total(), 0),
            (string) $order->get_total(),
            (string) $total_value,
            (string) round($total_value),
        ), static function ($value): bool {
            return is_string($value) && '' !== trim($value);
        })));

        $date_values = array_values(array_unique(array_filter(array(
            $created ? (string) $created->getTimestamp() : '',
            $created ? $created->date('Y-m-d H:i:s') : '',
            $created ? $created->date('c') : '',
        ), static function ($value): bool {
            return is_string($value) && '' !== trim($value);
        })));

        $labels = array('', 'lexi_invoice_verify', 'invoice_verify', 'lexi_verify', 'lexi_invoice', 'invoice');
        $templates = array(
            array($order_id),
            array($order_number),
            array($order_key),
            array($order_id, $order_key),
            array($order_id, $order_key, '{total}'),
            array($order_id, $order_key, '{date}'),
            array($order_id, $order_key, '{total}', '{date}'),
            array($order_id, '{total}'),
            array($order_id, '{total}', '{date}'),
            array($order_id, '{date}'),
            array($order_number, $order_id),
            array($order_id, $order_number),
            array($order_number, $order_key),
            array($order_number, $order_key, '{total}'),
            array($order_number, $order_key, '{total}', '{date}'),
        );

        if ('' !== $verify_token) {
            $templates[] = array($verify_token);
            $templates[] = array($order_id, $verify_token);
            $templates[] = array($order_id, $verify_token, '{date}');
            $templates[] = array($order_number, $verify_token);
            $templates[] = array($order_number, $verify_token, '{date}');
        }

        $payloads = array();
        foreach ($labels as $label) {
            foreach ($templates as $template) {
                $needs_total = in_array('{total}', $template, true);
                $needs_date = in_array('{date}', $template, true);

                $total_variants = $needs_total ? $totals : array('');
                $date_variants = $needs_date ? $date_values : array('');

                foreach ($total_variants as $total) {
                    foreach ($date_variants as $date_value) {
                        $parts = array();
                        if ('' !== $label) {
                            $parts[] = $label;
                        }

                        foreach ($template as $piece) {
                            if ('{total}' === $piece) {
                                $parts[] = (string) $total;
                                continue;
                            }
                            if ('{date}' === $piece) {
                                $parts[] = (string) $date_value;
                                continue;
                            }
                            $parts[] = (string) $piece;
                        }

                        foreach (self::join_components_with_separators($parts) as $payload) {
                            $payloads[] = $payload;
                        }
                    }
                }
            }
        }

        return array_values(array_unique(array_filter($payloads, static function ($payload): bool {
            return is_string($payload) && '' !== $payload;
        })));
    }

    /**
     * Generate candidate signatures for a payload.
     *
     * @param string $payload Signature payload.
     * @return array<int,string>
     */
    private static function build_signature_candidates(string $payload): array
    {
        $payload = trim($payload);
        if ('' === $payload) {
            return array();
        }

        $candidates = array();
        foreach (self::signature_secrets() as $secret) {
            if ('' === $secret) {
                continue;
            }

            $candidates[] = hash_hmac('sha256', $payload, $secret);
            $candidates[] = hash_hmac('sha1', $payload, $secret);
            $candidates[] = hash_hmac('md5', $payload, $secret);
            $candidates[] = hash('sha256', $payload . '|' . $secret);
            $candidates[] = hash('sha1', $payload . '|' . $secret);
            $candidates[] = hash('md5', $payload . '|' . $secret);
            $candidates[] = hash('sha256', $secret . '|' . $payload);
            $candidates[] = hash('sha1', $secret . '|' . $payload);
            $candidates[] = hash('md5', $secret . '|' . $payload);
        }

        // Some historical links were generated using non-HMAC hashing.
        $candidates[] = hash('sha256', $payload);
        $candidates[] = hash('sha1', $payload);
        $candidates[] = hash('md5', $payload);

        return array_values(array_unique(array_filter($candidates, static function ($candidate): bool {
            return is_string($candidate) && '' !== $candidate;
        })));
    }

    /**
     * Build candidate separators for legacy payloads.
     *
     * @param array<int,string> $parts Components to join.
     * @return array<int,string>
     */
    private static function join_components_with_separators(array $parts): array
    {
        $clean = array_values(array_filter(array_map(static function ($part): string {
            return trim((string) $part);
        }, $parts), static function ($part): bool {
            return '' !== $part;
        }));
        if (empty($clean)) {
            return array();
        }

        $joined = array();
        foreach (array('|', ':', ';', '-', '_', '', ' ') as $separator) {
            $joined[] = implode($separator, $clean);
        }

        return array_values(array_unique($joined));
    }

    /**
     * Known signing secrets used across old deployments.
     *
     * @return array<int,string>
     */
    private static function signature_secrets(): array
    {
        $secrets = array(
            (string) wp_salt('auth'),
            (string) wp_salt('secure_auth'),
            (string) wp_salt('logged_in'),
            (string) wp_salt('nonce'),
            (string) wp_salt(),
        );

        if (defined('AUTH_KEY')) {
            $secrets[] = (string) AUTH_KEY;
        }
        if (defined('AUTH_SALT')) {
            $secrets[] = (string) AUTH_SALT;
        }
        if (defined('SECURE_AUTH_KEY')) {
            $secrets[] = (string) SECURE_AUTH_KEY;
        }
        if (defined('SECURE_AUTH_SALT')) {
            $secrets[] = (string) SECURE_AUTH_SALT;
        }
        if (defined('LOGGED_IN_KEY')) {
            $secrets[] = (string) LOGGED_IN_KEY;
        }
        if (defined('LOGGED_IN_SALT')) {
            $secrets[] = (string) LOGGED_IN_SALT;
        }
        if (defined('NONCE_KEY')) {
            $secrets[] = (string) NONCE_KEY;
        }
        if (defined('NONCE_SALT')) {
            $secrets[] = (string) NONCE_SALT;
        }

        return array_values(array_unique(array_filter($secrets, static function ($secret): bool {
            return is_string($secret) && '' !== trim($secret);
        })));
    }

    /**
     * Determine which invoice type an order is eligible for.
     *
     * @param WC_Order $order WooCommerce order.
     * @return string "final" or "provisional".
     */
    public static function resolve_type(WC_Order $order): string
    {
        $final_statuses = array('processing', 'completed');
        if (in_array($order->get_status(), $final_statuses, true)) {
            return 'final';
        }
        return 'provisional';
    }

    /**
     * Resolve the brand logo URL from theme custom logo or site icon.
     */
    private static function resolve_brand_logo_url(): string
    {
        $custom_logo_id = (int) get_theme_mod('custom_logo');
        if ($custom_logo_id > 0) {
            $custom_logo = wp_get_attachment_image_url($custom_logo_id, 'medium');
            if (is_string($custom_logo) && '' !== trim($custom_logo)) {
                return esc_url_raw($custom_logo);
            }
        }

        $site_icon = get_site_icon_url(256);
        if (is_string($site_icon) && '' !== trim($site_icon)) {
            return esc_url_raw($site_icon);
        }

        return '';
    }

    /**
     * Render an Arabic HTML invoice.
     *
     * @param int    $order_id Order ID.
     * @param string $type     Invoice type.
     * @return string HTML content.
     */
    public static function render_html(int $order_id, string $type): string
    {
        $order = wc_get_order($order_id);
        if (!$order) {
            return "<!DOCTYPE html><html lang='ar' dir='rtl'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1'><title>الفاتورة</title><style>body{margin:0;background:#f3f4f6;font-family:'Cairo','Segoe UI',Tahoma,Arial,sans-serif;display:grid;place-items:center;min-height:100vh;color:#111827}.card{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:20px;max-width:560px;box-shadow:0 12px 28px rgba(0,0,0,.08)}h1{margin:0 0 8px;font-size:20px}p{margin:0;color:#475569}</style></head><body><div class='card'><h1>تعذر تحميل الفاتورة</h1><p>الطلب غير موجود.</p></div></body></html>";
        }

        $is_final = 'final' === $type;
        $title = $is_final ? 'فاتورة نهائية' : 'فاتورة مبدئية';
        $badge_color = $is_final ? '#16a34a' : '#f59e0b';
        $date = $order->get_date_created() ? $order->get_date_created()->date_i18n('Y-m-d H:i') : '';
        $order_number = (string) $order->get_order_number();

        $status_key = (string) $order->get_status();
        $status_map = array(
            'pending' => 'قيد الانتظار',
            'processing' => 'قيد المعالجة',
            'completed' => 'مكتمل',
            'cancelled' => 'ملغي',
            'failed' => 'فاشل',
            'refunded' => 'مسترجع',
            'on-hold' => 'معلق',
            'pending-verification' => 'بانتظار التحقق من الدفع',
            'out-for-delivery' => 'خرج للتسليم',
        );
        $status_label = isset($status_map[$status_key]) ? $status_map[$status_key] : wc_get_order_status_name($status_key);

        $format_amount = static function ($value): string {
            return number_format((float) $value, 2, '.', ',') . ' SYP';
        };

        $items_rows = '';
        foreach ($order->get_items() as $line_item) {
            if (!($line_item instanceof WC_Order_Item_Product)) {
                continue;
            }
            $product = $line_item->get_product();
            $qty = (int) $line_item->get_quantity();
            $line_total = (float) $line_item->get_total();
            $line_subtotal = (float) $line_item->get_subtotal();
            $unit_price = $qty > 0 ? ($line_subtotal / $qty) : 0.0;
            $name = esc_html(Lexi_Order_Flow::format_order_item_name($line_item));
            $sku = $product ? esc_html((string) $product->get_sku()) : '—';
            $items_rows .= "<tr><td class='cell product'>{$name}</td><td class='cell center'>{$sku}</td><td class='cell center'>{$qty}</td><td class='cell amount'>" . esc_html($format_amount($unit_price)) . "</td><td class='cell amount'>" . esc_html($format_amount($line_total)) . "</td></tr>";
        }
        if ('' === $items_rows) {
            $items_rows = "<tr><td class='cell muted center' colspan='5'>لا توجد بنود في هذه الفاتورة.</td></tr>";
        }

        $subtotal = (float) $order->get_subtotal();
        $shipping = (float) $order->get_shipping_total();
        $total = (float) $order->get_total();
        $payment_label = trim((string) $order->get_payment_method_title());
        if ('' === $payment_label) {
            $payment_label = 'غير محدد';
        }

        $billing_name = trim((string) $order->get_billing_first_name() . ' ' . (string) $order->get_billing_last_name());
        if ('' === $billing_name) {
            $billing_name = 'غير متوفر';
        }
        $billing_phone = trim((string) $order->get_billing_phone());
        if ('' === $billing_phone) {
            $billing_phone = 'غير متوفر';
        }
        $billing_address = trim((string) $order->get_billing_address_1());
        $billing_city = trim((string) $order->get_billing_city());
        $billing_addr = trim($billing_address . ($billing_city !== '' ? '، ' . $billing_city : ''));
        if ('' === $billing_addr) {
            $billing_addr = 'غير متوفر';
        }

        $store_name = esc_html((string) get_bloginfo('name'));
        $logo_url = self::resolve_brand_logo_url();
        $logo_html = '';
        if ('' !== $logo_url) {
            $logo_html = "<img src='" . esc_url($logo_url) . "' alt='شعار المتجر' class='brand-logo' />";
        }

        $verification_url = self::get_verification_url($order);
        $verification_qr_url = add_query_arg(
            array('data' => $verification_url, 'size' => 200),
            rest_url(LEXI_API_NAMESPACE . '/invoices/qr')
        );
        $verification_url_safe = esc_url($verification_url);
        $verification_qr_url_safe = esc_url($verification_qr_url);
        $verification_url_label = esc_html($verification_url);

        $html = "<!DOCTYPE html><html dir='rtl' lang='ar'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1'><title>{$title} - #{$order_number}</title><style>*{box-sizing:border-box}body{margin:0;background:#eef2f7;font-family:'Cairo','Segoe UI',Tahoma,Arial,sans-serif;color:#111827;line-height:1.65}.invoice{max-width:980px;margin:26px auto;background:#fff;border:1px solid #e5e7eb;border-radius:20px;overflow:hidden;box-shadow:0 20px 45px rgba(15,23,42,.12)}.hero{padding:24px 26px;background:linear-gradient(130deg,#0b1324 0%,#18233b 55%,#2a3c5e 100%);color:#fff}.hero-top{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap}.brand{display:flex;align-items:center;gap:12px}.brand-logo{width:52px;height:52px;border-radius:14px;background:#fff;padding:6px;object-fit:contain}.brand-title{font-size:24px;font-weight:800}.brand-sub{font-size:13px;opacity:.86}.badge{display:inline-flex;padding:6px 14px;border-radius:999px;background:{$badge_color};font-size:12px;font-weight:700}.hero-meta{margin-top:12px;display:flex;flex-wrap:wrap;gap:8px}.meta-chip{padding:6px 12px;border-radius:999px;background:rgba(255,255,255,.14);font-size:12px}.section{padding:22px 26px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.card{border:1px solid #e5e7eb;border-radius:14px;background:#f8fafc;padding:12px}.card-label{font-size:12px;color:#64748b}.card-value{font-size:15px;font-weight:800}.table-wrap{margin-top:12px;border:1px solid #e5e7eb;border-radius:14px;overflow:hidden}table{width:100%;border-collapse:collapse}thead th{padding:11px 10px;background:#f8fafc;color:#475569;font-size:12px;font-weight:700;text-align:right;border-bottom:1px solid #e5e7eb}.cell{padding:11px 10px;border-bottom:1px solid #eef2f7;font-size:13px}.product{font-weight:700}.center{text-align:center}.amount{text-align:left;direction:ltr}.muted{color:#64748b}.totals{margin-top:12px;border:1px solid #e5e7eb;border-radius:14px;padding:12px 14px;background:#fff}.total-row{display:flex;justify-content:space-between;padding:7px 0;font-size:14px}.total-final{margin-top:6px;padding-top:10px;border-top:1px solid #e5e7eb;font-size:18px;font-weight:800}.verify{margin-top:14px;border:1px solid #dbe7ff;border-radius:14px;background:linear-gradient(180deg,#f8fbff 0%,#f2f7ff 100%);padding:14px;display:flex;gap:16px;align-items:center;justify-content:space-between}.verify-title{font-size:17px;font-weight:800;margin:0}.verify-text{font-size:13px;color:#4b5563;margin:4px 0 8px}.verify-link{display:block;direction:ltr;text-align:left;color:#1d4ed8;text-decoration:none;word-break:break-all;font-size:12px}.verify-qr{width:128px;height:128px;background:#fff;border:1px solid #dbeafe;border-radius:10px;padding:8px}.verify-qr img{display:block;width:100%;height:100%}.footer{padding:14px 26px;background:#f8fafc;border-top:1px solid #e5e7eb;font-size:12px;color:#64748b}.footer p{margin:0}@media(max-width:860px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:640px){.invoice{margin:12px;border-radius:14px}.hero,.section,.footer{padding:16px}.grid{grid-template-columns:1fr}.verify{flex-direction:column;align-items:stretch}.verify-qr{width:120px;height:120px;align-self:flex-start}}</style></head><body><article class='invoice'><header class='hero'><div class='hero-top'><div class='brand'>{$logo_html}<div><div class='brand-title'>{$store_name}</div><div class='brand-sub'>{$title}</div></div></div><span class='badge'>{$title}</span></div><div class='hero-meta'><span class='meta-chip'>رقم الطلب: #" . esc_html($order_number) . "</span><span class='meta-chip'>الحالة: " . esc_html($status_label) . "</span><span class='meta-chip'>التاريخ: " . esc_html($date) . "</span></div></header><section class='section'><div class='grid'><div class='card'><div class='card-label'>العميل</div><div class='card-value'>" . esc_html($billing_name) . "</div></div><div class='card'><div class='card-label'>رقم الهاتف</div><div class='card-value'>" . esc_html($billing_phone) . "</div></div><div class='card'><div class='card-label'>طريقة الدفع</div><div class='card-value'>" . esc_html($payment_label) . "</div></div></div><div class='table-wrap'><table><thead><tr><th>المنتج</th><th class='center'>SKU</th><th class='center'>الكمية</th><th class='amount'>سعر الوحدة</th><th class='amount'>الإجمالي</th></tr></thead><tbody>{$items_rows}</tbody></table></div><div class='totals'><div class='total-row'><span>المجموع الفرعي</span><span>" . esc_html($format_amount($subtotal)) . "</span></div><div class='total-row'><span>الشحن</span><span>" . esc_html($format_amount($shipping)) . "</span></div><div class='total-row total-final'><span>الإجمالي النهائي</span><span>" . esc_html($format_amount($total)) . "</span></div></div><div class='verify'><div><p class='verify-title'>التحقق من صحة الفاتورة</p><p class='verify-text'>امسح رمز QR أو افتح الرابط التالي للتحقق من الفاتورة.</p><a class='verify-link' href='{$verification_url_safe}' rel='nofollow noopener'>{$verification_url_label}</a></div><div class='verify-qr'><img src='{$verification_qr_url_safe}' alt='رمز تحقق الفاتورة'></div></div><div class='card' style='margin-top:12px'><div class='card-label'>عنوان الفاتورة</div><div class='card-value'>" . esc_html($billing_addr) . "</div></div></section><footer class='footer'><p>{$title} — {$store_name} — " . esc_html($date) . "</p><p style='margin-top:4px'>هذه الفاتورة مولدة إلكترونياً ولا تحتاج إلى توقيع يدوي.</p></footer></article></body></html>";

        return $html;
    }
}

