// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUyqt4z1iroFAKvrV2a2N3ROYvU3YyX-M',
    appId: '1:753453474251:web:c68631bb46a3759df4d64e',
    messagingSenderId: '753453474251',
    projectId: 'leximeganew',
    authDomain: 'leximeganew.firebaseapp.com',
    storageBucket: 'leximeganew.firebasestorage.app',
    measurementId: 'G-V8JNHXSV2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgs3tWbmNBz6t21SVKXFvt19565wtFVSM',
    appId: '1:753453474251:android:f09b9c34135e68dff4d64e',
    messagingSenderId: '753453474251',
    projectId: 'leximeganew',
    storageBucket: 'leximeganew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFCvjUQNFGIl1LJXvKppg1z7XGnIunV_c',
    appId: '1:753453474251:ios:80bfaeac5c3600b1f4d64e',
    messagingSenderId: '753453474251',
    projectId: 'leximeganew',
    storageBucket: 'leximeganew.firebasestorage.app',
    iosBundleId: 'com.leximegastore.leximegastore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFCvjUQNFGIl1LJXvKppg1z7XGnIunV_c',
    appId: '1:753453474251:ios:80bfaeac5c3600b1f4d64e',
    messagingSenderId: '753453474251',
    projectId: 'leximeganew',
    storageBucket: 'leximeganew.firebasestorage.app',
    iosBundleId: 'com.leximegastore.leximegastore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUyqt4z1iroFAKvrV2a2N3ROYvU3YyX-M',
    appId: '1:753453474251:web:ded2b67225c6b169f4d64e',
    messagingSenderId: '753453474251',
    projectId: 'leximeganew',
    authDomain: 'leximeganew.firebaseapp.com',
    storageBucket: 'leximeganew.firebasestorage.app',
    measurementId: 'G-RHZ8V33XPR',
  );
}
